base_url = "https://embassy.dev/"
title = "Embassy"
description = "The next-generation framework for embedded applications. Write safe, correct and energy-efficient embedded code faster, using the Rust programming language, its async facilities, and the Embassy libraries."
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
minify_html = false
generate_feeds = true
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "material-dark" # OneHalfDark, material-dark, ayu-dark, Midnight.dark
render_emoji = false
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

[extra]
katex_enable = false # used to to render mathematical notations, requires js
recent = true
recent_items = 9
footer_credit = false
#google = "Your Google Site verification code."
#bing = "Your Bing Site verification code."
textlogo = 'Embassy'
sitedesc = false # This enables or disables the display of the site description below the logo.
author = "Embassy"
keywords = "embedded, framework, library, rust, async, stm32, nrf, nordic, rtos, operating system"
banner = "banner.png"
menu = [
    {url = "/", name = "About", slash = true},
    {url = "https://embassy.dev/book/", name = "Documentation", slash = false},
    {url = "https://docs.embassy.dev/", name = "API Reference", slash = false},
    
    {url = "/blog/", name = "Blog", slash = true},
    {url = "https://matrix.to/#/#embassy-rs:matrix.org", name = "Chat", slash = false},
    {url = "https://github.com/embassy-rs/embassy", name = "GitHub", slash = false},
    
#    {url = "/categories/", name = "Categories", slash = true},
#    {url = "/tags/", name = "Tags", slash = true},
]
menu_footer = [
    {url = "/privacy/", name = "Privacy", slash = true},
    {url = "/sitemap.xml", name = "Sitemap", slash = false},
]
# meta tags
twitter = "your-user-name"

# favicon = images/favicon.png  # override default favicon

# Footer social links; full options listed in macros/social.html
[extra.social]
github = "embassy-rs"
feed = true

#mail = "name@example.com"
#mastodon = "@your-user-name"
#element = "matrix.example.com"
##matrix = "matrix.example.com"
#twitter = "your-user-name"
#facebook = "your-user-name"
#linkedin = "your-user-name"
#gitlab = "your-user-name"
#bitbucket = "your-user-name"
#python = "your-user-name"
#docker = "your-user-name"
#stack = "your-user-name"
#instagram = "your-user-name"
#pinterest = "your-user-name"
#twitch = "your-user-name"
#youtube = "your-channel-id"
